### ISSUE TITLE
OpenDart Calling Issue

### ISSUE THREAD

**Issue by HaileyYoon23** [to-InfinityAndBeyond/ScreeingHelper#2]
[1/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 419.16, _last : 423.61, _lastlast : 426.47
2021-03-11 01:19:53
[2/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 202.67, _last : 130.54, _lastlast : 155.61
2021-03-11 01:20:02
[3/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 8.45, _last : 6.05, _lastlast : 18.32
2021-03-11 01:20:11
[4/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 248.93, _last : 184.2, _lastlast : 228.67
2021-03-11 01:20:21
[5/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:20:41
[6/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 59.76, _last : 81.25, _lastlast : 86.76
2021-03-11 01:20:49
[7/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:21:09
[8/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 176.3, _last : 153.39, _lastlast : 144.54
2021-03-11 01:21:17
[9/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 652.62, _last : 306.01, _lastlast : 216.35
2021-03-11 01:21:26
[10/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:21:48
[11/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 149.23, _last : 151.33, _lastlast : 127.77
2021-03-11 01:21:57
[12/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:22:20
[13/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:22:40
[14/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:23:03
[15/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 177.18, _last : 166.78, _lastlast : 174.55
2021-03-11 01:23:15
[16/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:23:32
[17/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 9.83, _last : 10.8, _lastlast : 12.25
2021-03-11 01:23:41
[18/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 72.12, _last : 109.65, _lastlast : 41.95
2021-03-11 01:23:50
[19/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:24:11
[20/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:24:33
[21/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 68.91, _last : 91.0, _lastlast : 118.07
2021-03-11 01:24:43
[22/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:25:06
[23/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:25:27
[24/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 82.11, _last : 84.86, _lastlast : 78.66
2021-03-11 01:25:36
[25/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 99.58, _last : 112.12, _lastlast : 135.37
2021-03-11 01:25:45
[26/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:26:05
[27/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:26:25
[28/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:26:46
[29/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 61.48, _last : 59.78, _lastlast : 54.99
2021-03-11 01:26:56
[30/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 54.77, _last : 52.59, _lastlast : 62.04
2021-03-11 01:27:05
[31/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:27:27
[32/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 198.76, _last : 170.95, _lastlast : 176.58
2021-03-11 01:27:36
[33/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 41.49, _last : 25.59, _lastlast : 35.19
2021-03-11 01:27:44
[34/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 55.41, _last : 36.24, _lastlast : 37.56
2021-03-11 01:27:54
[35/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 124.91, _last : 115.02, _lastlast : 127.72
2021-03-11 01:28:03
[36/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 217.91, _last : 231.98, _lastlast : 322.77
2021-03-11 01:28:13
[37/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 217.23, _last : 231.44, _lastlast : 260.58
2021-03-11 01:28:23
[38/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 176.57, _last : 107.41, _lastlast : 112.77
2021-03-11 01:28:32
[39/898] Updating pykrx/financial_statement
[debug] _valid : 0, _year : 0, _this : 0, _last : 0, _lastlast : 0
2021-03-11 01:28:53
[40/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 79.01, _last : 61.9, _lastlast : 120.74
2021-03-11 01:29:04
[41/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 40.68, _last : 39.69, _lastlast : 40.23
2021-03-11 01:29:12
[42/898] Updating pykrx/financial_statement
[debug] _valid : 1, _year : 2019, _this : 93.07, _last : 112.69, _lastlast : 118.96
2021-03-11 01:29:20
[43/898] Updating pykrx/financial_statement
Traceback (most recent call last):
  File "/Users/yoonseo/Documents/Dev/DB/MongoDB_pykrx/ScreeingHelper/StoreStockData/main.py", line 157, in <module>
    debt_ratio = get_debt_ratio(df)
  File "/Users/yoonseo/Documents/Dev/DB/MongoDB_pykrx/ScreeingHelper/StoreStockData/main.py", line 27, in get_debt_ratio
    debtratio = fs_df.loc[
  File "/Users/yoonseo/Documents/Dev/DB/MongoDB_pykrx/ScreeingHelper/StoreStockData/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 889, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/yoonseo/Documents/Dev/DB/MongoDB_pykrx/ScreeingHelper/StoreStockData/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1069, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/Users/yoonseo/Documents/Dev/DB/MongoDB_pykrx/ScreeingHelper/StoreStockData/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 775, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/Users/yoonseo/Documents/Dev/DB/MongoDB_pykrx/ScreeingHelper/StoreStockData/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/Users/yoonseo/Documents/Dev/DB/MongoDB_pykrx/ScreeingHelper/StoreStockData/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1053, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/Users/yoonseo/Documents/Dev/DB/MongoDB_pykrx/ScreeingHelper/StoreStockData/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/Users/yoonseo/Documents/Dev/DB/MongoDB_pykrx/ScreeingHelper/StoreStockData/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1321, in _validate_read_indexer
    raise KeyError(
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['bfefrmtrm_amount'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

**Comment by codingple** [comment]
Improvement
1. error shown above is resolved by 'get_debt_ratio' returns None when cannot get loc in line 27
2. 'get_dart_primary_num' added: out from 'opendart_finance' for redundant invoking
3. set try-except in 'get_debt_ratio', preventing from errors
(to-do : separate each error at except)

**Comment by HaileyYoon23** [comment]
Resolve Checked
